language: ruby

rvm:
- ruby-head
- 2.4.1
- 2.3.4
- 2.2.7
- 2.1.10

before_install:
  - mkdir ~/sources
  - git clone https://github.com/ONLYOFFICE/api.onlyoffice.com.git ~/sources/api.onlyoffice.com

script:
  - bundle exec rspec
