language: ruby

rvm:
- ruby-head
- 2.5.0
- 2.4.3
- 2.3.6
- 2.2.9
- 2.1.10

before_install:
  - gem update --system
  - mkdir ~/sources
  - git clone https://github.com/ONLYOFFICE/api.onlyoffice.com.git ~/sources/api.onlyoffice.com

script:
  - bundle exec rspec
